# Generated by Django 3.0.1 on 2020-01-01 06:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_auto_20191231_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 6, 34, 42, 274095, tzinfo=utc)),
        ),
    ]
