# Generated by Django 3.0.1 on 2020-01-02 05:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_auto_20200101_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 2, 5, 4, 6, 849613, tzinfo=utc)),
        ),
    ]
