# Generated by Django 3.0.1 on 2020-01-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=50)),
                ('blog_desc', models.CharField(max_length=500)),
                ('blog_date', models.DateField()),
            ],
        ),
    ]
