# Generated by Django 3.0.1 on 2020-01-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_desc', models.TextField()),
                ('product_price', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='pics')),
                ('product_avail', models.BooleanField(default=False)),
            ],
        ),
    ]
